require("core.packer")
require("core.mappings")
require("core.settings")

require("plugins.autopairs")
require("plugins.filetree")
require("plugins.lsp.language-servers")
require("plugins.lsp.nvim-cmp")
require("plugins.lsp.lspsaga")
require("plugins.lualine")
require("plugins.telescope")
require("plugins.toggleterm")
require("plugins.catppuccin")
require("plugins.bufferline")
require("plugins.treesitter")
require("plugins.autotag")
require("plugins.mason")
